### ISSUE TITLE
Added your work to projects page!

### ISSUE THREAD

**Issue by thomasdavis** [kelvintaywl/jsonresume-validator#2]
http://jsonresume.org/projects/

Thanks for the contributions! Funny to see a python dev straying over to a bunch of js devs =D

**Comment by kelvintaywl** [comment]
Hey @thomasdavis ,

Thanks for the shoutout! Really appreciate it :)

Haha, well I particularly enjoy what JSON Resume is trying to achieve as a community and wanted the Python community to know about this hopefully!

**Comment by kelvintaywl** [comment]
i also added a sample Flask app (python) @ https://github.com/kelvintaywl/jsonresume-server showcasing the validation tool, as well as informing users of the JSON Resume initiative. hopefully, this helps for greater traction!
